# Generated by Django 5.0.3 on 2024-10-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(verbose_name='Numero de Pedido'),
        ),
    ]
